# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjAyMDEzODA0N2IzZDNhOGVkMDc4MTg1YjBjYWRhNWE1NTA3YTU3OWRmNWViMzA2YWFiZGYwM2ZmNjlkYzRkMWE5NmU5ZWZhMGFiMDg5M2ZlNDU1MjI4MDI2MzlhODI4NTQ5YzY0M2VmMTc1MGMxMjdkOTBiNzgzMjkyZGFhNTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
